# Generated by Django 3.2.12 on 2022-04-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220406_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='suummary',
            new_name='summary',
        ),
    ]
